# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PyQtDesinger_GUIkEilXc.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

import Ressourcen_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1922, 1080)
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QIcon()
        iconThemeName = u"Demonstrator"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u":/h-ka Logos/Ressourcen/favicon.ico", QSize(), QIcon.Normal, QIcon.On)
        
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setStyleSheet(u"QMainWindow {\n"
"	background: white;\n"
"}")
        self.actionWas_ist_das = QAction(MainWindow)
        self.actionWas_ist_das.setObjectName(u"actionWas_ist_das")
        self.actionVollbild = QAction(MainWindow)
        self.actionVollbild.setObjectName(u"actionVollbild")
        self.actionFenster = QAction(MainWindow)
        self.actionFenster.setObjectName(u"actionFenster")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblTitel = QLabel(self.centralwidget)
        self.lblTitel.setObjectName(u"lblTitel")
        self.lblTitel.setGeometry(QRect(10, 10, 451, 31))
        self.lblHKALogo = QLabel(self.centralwidget)
        self.lblHKALogo.setObjectName(u"lblHKALogo")
        self.lblHKALogo.setGeometry(QRect(10, 990, 521, 81))
        self.btnClose = QDialogButtonBox(self.centralwidget)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(1850, 0, 71, 23))
        self.btnClose.setStandardButtons(QDialogButtonBox.Close)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 60, 1901, 901))
        font1 = QFont()
        font1.setFamily(u"MS Shell Dlg 2")
        font1.setPointSize(12)
        self.tabWidget.setFont(font1)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"/* Tab-Liste Allgemein: */\n"
"QTabBar::tab {\n"
"   	width: 15em;\n"
"	height: 3em;\n"
"    border-top-left-radius: 0.5em;\n"
"    border-top-right-radius: 0.5em;\n"
"	margin-right: 0.5em;		/* Abstand zwischen den Tabs */\n"
"}\n"
"\n"
"/* Style wenn Tab ausgew\u00e4hlt: */\n"
"QTabBar::tab:selected {\n"
"    background-color: #d9d9d9; 		/* Hellgrau */\n"
"    border: 1px solid #d72305;		/* Roter Rahmen */\n"
"	border-bottom-color: #d9d9d9;	/* Hellgrau */\n"
"}\n"
"\n"
"/* Style wenn Tab nicht ausgew\u00e4hlt: */\n"
"QTabBar::tab:!selected {\n"
"    background-color: #a4a4a4;		/* Dunkelgrau */\n"
"    border: 1px solid #d72305;		/* Roter Rahmen */\n"
"	border-bottom-color: #a4a4a4;	/* Dunkelgrau */\n"
"}\n"
"\n"
"/* Tab-Fenster: */\n"
"QTabWidget:pane {\n"
"	top: -1px;								/* Tab-Fenster 1 Pixel nach oben schieben, um den Rahmen zwischen Tab und Fenster zu \u00fcberlappen*/\n"
"	background: #d9d9d9;			/* Hellgrau */\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"")
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setIconSize(QSize(16, 16))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.Spielfeld = QWidget()
        self.Spielfeld.setObjectName(u"Spielfeld")
        self.lblSpielfeld = QLabel(self.Spielfeld)
        self.lblSpielfeld.setObjectName(u"lblSpielfeld")
        self.lblSpielfeld.setGeometry(QRect(520, 0, 861, 861))
        self.lblSt00 = QLabel(self.Spielfeld)
        self.lblSt00.setObjectName(u"lblSt00")
        self.lblSt00.setGeometry(QRect(538, 17, 45, 45))
        self.lblSt01 = QLabel(self.Spielfeld)
        self.lblSt01.setObjectName(u"lblSt01")
        self.lblSt01.setGeometry(QRect(928, 16, 45, 45))
        self.lblSt02 = QLabel(self.Spielfeld)
        self.lblSt02.setObjectName(u"lblSt02")
        self.lblSt02.setGeometry(QRect(1318, 16, 45, 45))
        self.lblSt10 = QLabel(self.Spielfeld)
        self.lblSt10.setObjectName(u"lblSt10")
        self.lblSt10.setGeometry(QRect(668, 148, 45, 45))
        self.lblSt11 = QLabel(self.Spielfeld)
        self.lblSt11.setObjectName(u"lblSt11")
        self.lblSt11.setGeometry(QRect(928, 148, 45, 45))
        self.lblSt12 = QLabel(self.Spielfeld)
        self.lblSt12.setObjectName(u"lblSt12")
        self.lblSt12.setGeometry(QRect(1188, 148, 45, 45))
        self.lblSt20 = QLabel(self.Spielfeld)
        self.lblSt20.setObjectName(u"lblSt20")
        self.lblSt20.setGeometry(QRect(798, 278, 45, 45))
        self.lblSt21 = QLabel(self.Spielfeld)
        self.lblSt21.setObjectName(u"lblSt21")
        self.lblSt21.setGeometry(QRect(928, 278, 45, 45))
        self.lblSt22 = QLabel(self.Spielfeld)
        self.lblSt22.setObjectName(u"lblSt22")
        self.lblSt22.setGeometry(QRect(1058, 278, 45, 45))
        self.lblSt13 = QLabel(self.Spielfeld)
        self.lblSt13.setObjectName(u"lblSt13")
        self.lblSt13.setGeometry(QRect(1188, 408, 45, 45))
        self.lblSt03 = QLabel(self.Spielfeld)
        self.lblSt03.setObjectName(u"lblSt03")
        self.lblSt03.setGeometry(QRect(1318, 408, 45, 45))
        self.lblSt23 = QLabel(self.Spielfeld)
        self.lblSt23.setObjectName(u"lblSt23")
        self.lblSt23.setGeometry(QRect(1058, 408, 45, 45))
        self.lblSt24 = QLabel(self.Spielfeld)
        self.lblSt24.setObjectName(u"lblSt24")
        self.lblSt24.setGeometry(QRect(1058, 538, 45, 45))
        self.lblSt25 = QLabel(self.Spielfeld)
        self.lblSt25.setObjectName(u"lblSt25")
        self.lblSt25.setGeometry(QRect(928, 538, 45, 45))
        self.lblSt26 = QLabel(self.Spielfeld)
        self.lblSt26.setObjectName(u"lblSt26")
        self.lblSt26.setGeometry(QRect(798, 538, 45, 45))
        self.lblSt27 = QLabel(self.Spielfeld)
        self.lblSt27.setObjectName(u"lblSt27")
        self.lblSt27.setGeometry(QRect(798, 408, 45, 45))
        self.lblSt04 = QLabel(self.Spielfeld)
        self.lblSt04.setObjectName(u"lblSt04")
        self.lblSt04.setGeometry(QRect(1318, 798, 45, 45))
        self.lblSt05 = QLabel(self.Spielfeld)
        self.lblSt05.setObjectName(u"lblSt05")
        self.lblSt05.setGeometry(QRect(928, 798, 45, 45))
        self.lblSt06 = QLabel(self.Spielfeld)
        self.lblSt06.setObjectName(u"lblSt06")
        self.lblSt06.setGeometry(QRect(538, 798, 45, 45))
        self.lblSt07 = QLabel(self.Spielfeld)
        self.lblSt07.setObjectName(u"lblSt07")
        self.lblSt07.setGeometry(QRect(538, 408, 45, 45))
        self.lblSt14 = QLabel(self.Spielfeld)
        self.lblSt14.setObjectName(u"lblSt14")
        self.lblSt14.setGeometry(QRect(1188, 668, 45, 45))
        self.lblSt15 = QLabel(self.Spielfeld)
        self.lblSt15.setObjectName(u"lblSt15")
        self.lblSt15.setGeometry(QRect(928, 668, 45, 45))
        self.lblSt16 = QLabel(self.Spielfeld)
        self.lblSt16.setObjectName(u"lblSt16")
        self.lblSt16.setGeometry(QRect(668, 668, 45, 45))
        self.lblSt17 = QLabel(self.Spielfeld)
        self.lblSt17.setObjectName(u"lblSt17")
        self.lblSt17.setGeometry(QRect(668, 408, 45, 45))
        self.lblTxtAvTokens = QLabel(self.Spielfeld)
        self.lblTxtAvTokens.setObjectName(u"lblTxtAvTokens")
        self.lblTxtAvTokens.setGeometry(QRect(340, 15, 171, 20))
        self.lblAvP20 = QLabel(self.Spielfeld)
        self.lblAvP20.setObjectName(u"lblAvP20")
        self.lblAvP20.setGeometry(QRect(420, 50, 45, 45))
        self.lblAvP21 = QLabel(self.Spielfeld)
        self.lblAvP21.setObjectName(u"lblAvP21")
        self.lblAvP21.setGeometry(QRect(420, 100, 45, 45))
        self.lblAvP22 = QLabel(self.Spielfeld)
        self.lblAvP22.setObjectName(u"lblAvP22")
        self.lblAvP22.setGeometry(QRect(420, 150, 45, 45))
        self.lblAvP23 = QLabel(self.Spielfeld)
        self.lblAvP23.setObjectName(u"lblAvP23")
        self.lblAvP23.setGeometry(QRect(420, 200, 45, 45))
        self.lblAvP24 = QLabel(self.Spielfeld)
        self.lblAvP24.setObjectName(u"lblAvP24")
        self.lblAvP24.setGeometry(QRect(420, 250, 45, 45))
        self.lblAvP25 = QLabel(self.Spielfeld)
        self.lblAvP25.setObjectName(u"lblAvP25")
        self.lblAvP25.setGeometry(QRect(420, 300, 45, 45))
        self.lblAvP26 = QLabel(self.Spielfeld)
        self.lblAvP26.setObjectName(u"lblAvP26")
        self.lblAvP26.setGeometry(QRect(420, 350, 45, 45))
        self.lblAvP27 = QLabel(self.Spielfeld)
        self.lblAvP27.setObjectName(u"lblAvP27")
        self.lblAvP27.setGeometry(QRect(420, 400, 45, 45))
        self.lblAvP28 = QLabel(self.Spielfeld)
        self.lblAvP28.setObjectName(u"lblAvP28")
        self.lblAvP28.setGeometry(QRect(420, 450, 45, 45))
        self.lblAvP12 = QLabel(self.Spielfeld)
        self.lblAvP12.setObjectName(u"lblAvP12")
        self.lblAvP12.setGeometry(QRect(370, 150, 45, 45))
        self.lblAvP11 = QLabel(self.Spielfeld)
        self.lblAvP11.setObjectName(u"lblAvP11")
        self.lblAvP11.setGeometry(QRect(370, 100, 45, 45))
        self.lblAvP14 = QLabel(self.Spielfeld)
        self.lblAvP14.setObjectName(u"lblAvP14")
        self.lblAvP14.setGeometry(QRect(370, 250, 45, 45))
        self.lblAvP10 = QLabel(self.Spielfeld)
        self.lblAvP10.setObjectName(u"lblAvP10")
        self.lblAvP10.setGeometry(QRect(370, 50, 45, 45))
        self.lblAvP13 = QLabel(self.Spielfeld)
        self.lblAvP13.setObjectName(u"lblAvP13")
        self.lblAvP13.setGeometry(QRect(370, 200, 45, 45))
        self.lblAvP16 = QLabel(self.Spielfeld)
        self.lblAvP16.setObjectName(u"lblAvP16")
        self.lblAvP16.setGeometry(QRect(370, 350, 45, 45))
        self.lblAvP17 = QLabel(self.Spielfeld)
        self.lblAvP17.setObjectName(u"lblAvP17")
        self.lblAvP17.setGeometry(QRect(370, 400, 45, 45))
        self.lblAvP18 = QLabel(self.Spielfeld)
        self.lblAvP18.setObjectName(u"lblAvP18")
        self.lblAvP18.setGeometry(QRect(370, 450, 45, 45))
        self.lblAvP15 = QLabel(self.Spielfeld)
        self.lblAvP15.setObjectName(u"lblAvP15")
        self.lblAvP15.setGeometry(QRect(370, 300, 45, 45))
        self.btnRestart = QPushButton(self.Spielfeld)
        self.btnRestart.setObjectName(u"btnRestart")
        self.btnRestart.setGeometry(QRect(1390, 20, 131, 41))
        self.lblNextAction = QLabel(self.Spielfeld)
        self.lblNextAction.setObjectName(u"lblNextAction")
        self.lblNextAction.setGeometry(QRect(1400, 100, 491, 21))
        self.lblTxtNextAction = QLabel(self.Spielfeld)
        self.lblTxtNextAction.setObjectName(u"lblTxtNextAction")
        self.lblTxtNextAction.setGeometry(QRect(1390, 75, 161, 20))
        self.tabWidget.addTab(self.Spielfeld, "")
        self.Einstellungen = QWidget()
        self.Einstellungen.setObjectName(u"Einstellungen")
        self.gbPlayer = QGroupBox(self.Einstellungen)
        self.gbPlayer.setObjectName(u"gbPlayer")
        self.gbPlayer.setGeometry(QRect(10, 50, 601, 201))
        font2 = QFont()
        font2.setPointSize(12)
        self.gbPlayer.setFont(font2)
        self.gbPlayer.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.rBtnPlayer1Human = QRadioButton(self.gbPlayer)
        self.btnGroupPlayer1 = QButtonGroup(MainWindow)
        self.btnGroupPlayer1.setObjectName(u"btnGroupPlayer1")
        self.btnGroupPlayer1.addButton(self.rBtnPlayer1Human)
        self.rBtnPlayer1Human.setObjectName(u"rBtnPlayer1Human")
        self.rBtnPlayer1Human.setGeometry(QRect(20, 40, 191, 20))
        self.rBtnPlayer1Human.setFont(font2)
        self.rBtnPlayer1Human.setChecked(True)
        self.rBtnPlayer1KI = QRadioButton(self.gbPlayer)
        self.btnGroupPlayer1.addButton(self.rBtnPlayer1KI)
        self.rBtnPlayer1KI.setObjectName(u"rBtnPlayer1KI")
        self.rBtnPlayer1KI.setGeometry(QRect(20, 60, 191, 20))
        self.rBtnPlayer1KI.setFont(font2)
        self.rBtnPlayer1KI.setAutoRepeat(False)
        self.rBtnPlayer1KI.setAutoExclusive(False)
        self.lblTxtNextAction_2 = QLabel(self.gbPlayer)
        self.lblTxtNextAction_2.setObjectName(u"lblTxtNextAction_2")
        self.lblTxtNextAction_2.setGeometry(QRect(10, 20, 161, 20))
        self.lblTxtNextAction_3 = QLabel(self.gbPlayer)
        self.lblTxtNextAction_3.setObjectName(u"lblTxtNextAction_3")
        self.lblTxtNextAction_3.setGeometry(QRect(10, 110, 161, 20))
        self.rBtnPlayer2Human = QRadioButton(self.gbPlayer)
        self.btnGroupPlayer2 = QButtonGroup(MainWindow)
        self.btnGroupPlayer2.setObjectName(u"btnGroupPlayer2")
        self.btnGroupPlayer2.addButton(self.rBtnPlayer2Human)
        self.rBtnPlayer2Human.setObjectName(u"rBtnPlayer2Human")
        self.rBtnPlayer2Human.setGeometry(QRect(20, 130, 191, 20))
        self.rBtnPlayer2Human.setFont(font2)
        self.rBtnPlayer2Human.setChecked(True)
        self.rBtnPlayer2KI = QRadioButton(self.gbPlayer)
        self.btnGroupPlayer2.addButton(self.rBtnPlayer2KI)
        self.rBtnPlayer2KI.setObjectName(u"rBtnPlayer2KI")
        self.rBtnPlayer2KI.setGeometry(QRect(20, 150, 191, 20))
        self.rBtnPlayer2KI.setFont(font2)
        self.btnLoadKIData1 = QPushButton(self.gbPlayer)
        self.btnLoadKIData1.setObjectName(u"btnLoadKIData1")
        self.btnLoadKIData1.setGeometry(QRect(100, 60, 100, 25))
        self.btnLoadKIData2 = QPushButton(self.gbPlayer)
        self.btnLoadKIData2.setObjectName(u"btnLoadKIData2")
        self.btnLoadKIData2.setGeometry(QRect(100, 150, 100, 25))
        self.lblTxtLoadeFilePath1 = QLabel(self.gbPlayer)
        self.lblTxtLoadeFilePath1.setObjectName(u"lblTxtLoadeFilePath1")
        self.lblTxtLoadeFilePath1.setGeometry(QRect(40, 85, 561, 20))
        self.lblTxtLoadeFilePath2 = QLabel(self.gbPlayer)
        self.lblTxtLoadeFilePath2.setObjectName(u"lblTxtLoadeFilePath2")
        self.lblTxtLoadeFilePath2.setGeometry(QRect(40, 175, 561, 20))
        self.btnSettingSave = QPushButton(self.Einstellungen)
        self.btnSettingSave.setObjectName(u"btnSettingSave")
        self.btnSettingSave.setGeometry(QRect(10, 10, 131, 31))
        self.gbPlayer_2 = QGroupBox(self.Einstellungen)
        self.gbPlayer_2.setObjectName(u"gbPlayer_2")
        self.gbPlayer_2.setGeometry(QRect(10, 260, 601, 71))
        self.gbPlayer_2.setFont(font2)
        self.gbPlayer_2.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.dsBoxTimeAIvsAI = QDoubleSpinBox(self.gbPlayer_2)
        self.dsBoxTimeAIvsAI.setObjectName(u"dsBoxTimeAIvsAI")
        self.dsBoxTimeAIvsAI.setGeometry(QRect(250, 30, 100, 22))
        self.dsBoxTimeAIvsAI.setFont(font2)
        self.dsBoxTimeAIvsAI.setDecimals(1)
        self.dsBoxTimeAIvsAI.setMaximum(10.000000000000000)
        self.dsBoxTimeAIvsAI.setSingleStep(0.010000000000000)
        self.dsBoxTimeAIvsAI.setValue(1.000000000000000)
        self.lblTxtNumberGames_17 = QLabel(self.gbPlayer_2)
        self.lblTxtNumberGames_17.setObjectName(u"lblTxtNumberGames_17")
        self.lblTxtNumberGames_17.setGeometry(QRect(10, 30, 241, 21))
        self.lblTxtNumberGames_18 = QLabel(self.gbPlayer_2)
        self.lblTxtNumberGames_18.setObjectName(u"lblTxtNumberGames_18")
        self.lblTxtNumberGames_18.setGeometry(QRect(360, 30, 21, 21))
        self.tabWidget.addTab(self.Einstellungen, "")
        self.Training = QWidget()
        self.Training.setObjectName(u"Training")
        self.gbTrainingParameter = QGroupBox(self.Training)
        self.gbTrainingParameter.setObjectName(u"gbTrainingParameter")
        self.gbTrainingParameter.setGeometry(QRect(10, 10, 391, 841))
        self.gbTrainingParameter.setFont(font2)
        self.gbTrainingParameter.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.cBoxTrainPhase3 = QCheckBox(self.gbTrainingParameter)
        self.cBoxTrainPhase3.setObjectName(u"cBoxTrainPhase3")
        self.cBoxTrainPhase3.setGeometry(QRect(10, 220, 340, 20))
        self.cBoxTrainPhase3.setFont(font2)
        self.cBoxTrainPhase3.setChecked(True)
        self.sBoxNumberGames = QSpinBox(self.gbTrainingParameter)
        self.sBoxNumberGames.setObjectName(u"sBoxNumberGames")
        self.sBoxNumberGames.setGeometry(QRect(250, 110, 100, 22))
        self.sBoxNumberGames.setFont(font2)
        self.sBoxNumberGames.setMinimum(1)
        self.sBoxNumberGames.setMaximum(99999999)
        self.sBoxNumberGames.setValue(1000)
        self.sBoxNumberGames.setDisplayIntegerBase(10)
        self.lblTxtMaxMoves = QLabel(self.gbTrainingParameter)
        self.lblTxtMaxMoves.setObjectName(u"lblTxtMaxMoves")
        self.lblTxtMaxMoves.setGeometry(QRect(10, 140, 241, 21))
        self.cBoxTrainPhase1 = QCheckBox(self.gbTrainingParameter)
        self.cBoxTrainPhase1.setObjectName(u"cBoxTrainPhase1")
        self.cBoxTrainPhase1.setGeometry(QRect(10, 170, 340, 20))
        self.cBoxTrainPhase1.setFont(font2)
        self.cBoxTrainPhase1.setChecked(True)
        self.lblTxtNumberGames = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames.setObjectName(u"lblTxtNumberGames")
        self.lblTxtNumberGames.setGeometry(QRect(10, 110, 241, 21))
        self.sBoxMaxMoves = QSpinBox(self.gbTrainingParameter)
        self.sBoxMaxMoves.setObjectName(u"sBoxMaxMoves")
        self.sBoxMaxMoves.setGeometry(QRect(250, 140, 100, 22))
        self.sBoxMaxMoves.setFont(font2)
        self.sBoxMaxMoves.setMinimum(1)
        self.sBoxMaxMoves.setMaximum(999)
        self.sBoxMaxMoves.setValue(200)
        self.cBoxTrainPhase2 = QCheckBox(self.gbTrainingParameter)
        self.cBoxTrainPhase2.setObjectName(u"cBoxTrainPhase2")
        self.cBoxTrainPhase2.setGeometry(QRect(10, 195, 340, 20))
        self.cBoxTrainPhase2.setFont(font2)
        self.cBoxTrainPhase2.setChecked(True)
        self.lblTxtTrainingSince_2 = QLabel(self.gbTrainingParameter)
        self.lblTxtTrainingSince_2.setObjectName(u"lblTxtTrainingSince_2")
        self.lblTxtTrainingSince_2.setGeometry(QRect(10, 260, 341, 21))
        self.sBoxRewardMove = QSpinBox(self.gbTrainingParameter)
        self.sBoxRewardMove.setObjectName(u"sBoxRewardMove")
        self.sBoxRewardMove.setGeometry(QRect(250, 290, 100, 22))
        self.sBoxRewardMove.setFont(font2)
        self.sBoxRewardMove.setMinimum(-1000)
        self.sBoxRewardMove.setMaximum(1000)
        self.sBoxRewardMove.setValue(-1)
        self.lblTxtNumberGames_2 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_2.setObjectName(u"lblTxtNumberGames_2")
        self.lblTxtNumberGames_2.setGeometry(QRect(10, 290, 241, 21))
        self.lblTxtNumberGames_3 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_3.setObjectName(u"lblTxtNumberGames_3")
        self.lblTxtNumberGames_3.setGeometry(QRect(10, 320, 241, 21))
        self.sBoxRewardOwnMill = QSpinBox(self.gbTrainingParameter)
        self.sBoxRewardOwnMill.setObjectName(u"sBoxRewardOwnMill")
        self.sBoxRewardOwnMill.setGeometry(QRect(250, 320, 100, 22))
        self.sBoxRewardOwnMill.setFont(font2)
        self.sBoxRewardOwnMill.setMinimum(-10000)
        self.sBoxRewardOwnMill.setMaximum(10000)
        self.sBoxRewardOwnMill.setValue(200)
        self.sBoxRewardEnemyMill = QSpinBox(self.gbTrainingParameter)
        self.sBoxRewardEnemyMill.setObjectName(u"sBoxRewardEnemyMill")
        self.sBoxRewardEnemyMill.setGeometry(QRect(250, 350, 100, 22))
        self.sBoxRewardEnemyMill.setFont(font2)
        self.sBoxRewardEnemyMill.setMinimum(-10000)
        self.sBoxRewardEnemyMill.setMaximum(10000)
        self.sBoxRewardEnemyMill.setValue(-200)
        self.lblTxtNumberGames_4 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_4.setObjectName(u"lblTxtNumberGames_4")
        self.lblTxtNumberGames_4.setGeometry(QRect(10, 350, 241, 21))
        self.lblTxtNumberGames_5 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_5.setObjectName(u"lblTxtNumberGames_5")
        self.lblTxtNumberGames_5.setGeometry(QRect(10, 380, 241, 21))
        self.sBoxRewardWin = QSpinBox(self.gbTrainingParameter)
        self.sBoxRewardWin.setObjectName(u"sBoxRewardWin")
        self.sBoxRewardWin.setGeometry(QRect(250, 380, 100, 22))
        self.sBoxRewardWin.setFont(font2)
        self.sBoxRewardWin.setMinimum(-10000)
        self.sBoxRewardWin.setMaximum(10000)
        self.sBoxRewardWin.setValue(5000)
        self.sBoxRewardLoss = QSpinBox(self.gbTrainingParameter)
        self.sBoxRewardLoss.setObjectName(u"sBoxRewardLoss")
        self.sBoxRewardLoss.setGeometry(QRect(250, 410, 100, 22))
        self.sBoxRewardLoss.setFont(font2)
        self.sBoxRewardLoss.setMinimum(-10000)
        self.sBoxRewardLoss.setMaximum(10000)
        self.sBoxRewardLoss.setValue(-5000)
        self.lblTxtNumberGames_6 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_6.setObjectName(u"lblTxtNumberGames_6")
        self.lblTxtNumberGames_6.setGeometry(QRect(10, 410, 241, 21))
        self.dsBoxEpsilonDecay = QDoubleSpinBox(self.gbTrainingParameter)
        self.dsBoxEpsilonDecay.setObjectName(u"dsBoxEpsilonDecay")
        self.dsBoxEpsilonDecay.setGeometry(QRect(250, 550, 100, 22))
        self.dsBoxEpsilonDecay.setFont(font2)
        self.dsBoxEpsilonDecay.setDecimals(5)
        self.dsBoxEpsilonDecay.setMaximum(1.000000000000000)
        self.dsBoxEpsilonDecay.setSingleStep(0.000010000000000)
        self.dsBoxEpsilonDecay.setValue(0.999750000000000)
        self.lblTxtNumberGames_8 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_8.setObjectName(u"lblTxtNumberGames_8")
        self.lblTxtNumberGames_8.setGeometry(QRect(10, 550, 241, 21))
        self.dsBoxEpsilon = QDoubleSpinBox(self.gbTrainingParameter)
        self.dsBoxEpsilon.setObjectName(u"dsBoxEpsilon")
        self.dsBoxEpsilon.setGeometry(QRect(250, 520, 100, 22))
        self.dsBoxEpsilon.setFont(font2)
        self.dsBoxEpsilon.setMaximum(1.000000000000000)
        self.dsBoxEpsilon.setSingleStep(0.010000000000000)
        self.dsBoxEpsilon.setValue(1.000000000000000)
        self.btnSaveTrainingParameter = QPushButton(self.gbTrainingParameter)
        self.btnSaveTrainingParameter.setObjectName(u"btnSaveTrainingParameter")
        self.btnSaveTrainingParameter.setGeometry(QRect(150, 30, 131, 41))
        self.btnLoadTrainingParameter = QPushButton(self.gbTrainingParameter)
        self.btnLoadTrainingParameter.setObjectName(u"btnLoadTrainingParameter")
        self.btnLoadTrainingParameter.setGeometry(QRect(10, 30, 131, 41))
        self.btnLoadTrainingParameter.setMouseTracking(False)
        self.btnLoadTrainingParameter.setToolTipDuration(-1)
        self.btnLoadTrainingParameter.setCheckable(False)
        self.btnLoadTrainingParameter.setFlat(False)
        self.lblTxtLoadedTrainingsParameter = QLabel(self.gbTrainingParameter)
        self.lblTxtLoadedTrainingsParameter.setObjectName(u"lblTxtLoadedTrainingsParameter")
        self.lblTxtLoadedTrainingsParameter.setGeometry(QRect(10, 80, 381, 21))
        self.sBoxNumTrainingInstances = QSpinBox(self.gbTrainingParameter)
        self.sBoxNumTrainingInstances.setObjectName(u"sBoxNumTrainingInstances")
        self.sBoxNumTrainingInstances.setGeometry(QRect(250, 620, 100, 22))
        self.sBoxNumTrainingInstances.setFont(font2)
        self.sBoxNumTrainingInstances.setMinimum(1)
        self.sBoxNumTrainingInstances.setMaximum(1000)
        self.sBoxNumTrainingInstances.setValue(32)
        self.lblTxtNumberGames_9 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_9.setObjectName(u"lblTxtNumberGames_9")
        self.lblTxtNumberGames_9.setGeometry(QRect(10, 620, 241, 21))
        self.sBoxMinReplayMemorySize = QSpinBox(self.gbTrainingParameter)
        self.sBoxMinReplayMemorySize.setObjectName(u"sBoxMinReplayMemorySize")
        self.sBoxMinReplayMemorySize.setGeometry(QRect(250, 650, 100, 22))
        self.sBoxMinReplayMemorySize.setFont(font2)
        self.sBoxMinReplayMemorySize.setMinimum(1)
        self.sBoxMinReplayMemorySize.setMaximum(100000)
        self.sBoxMinReplayMemorySize.setValue(1024)
        self.lblTxtNumberGames_10 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_10.setObjectName(u"lblTxtNumberGames_10")
        self.lblTxtNumberGames_10.setGeometry(QRect(10, 650, 241, 21))
        self.dsBoxEpsilonMin = QDoubleSpinBox(self.gbTrainingParameter)
        self.dsBoxEpsilonMin.setObjectName(u"dsBoxEpsilonMin")
        self.dsBoxEpsilonMin.setGeometry(QRect(250, 580, 100, 22))
        self.dsBoxEpsilonMin.setFont(font2)
        self.dsBoxEpsilonMin.setDecimals(5)
        self.dsBoxEpsilonMin.setMaximum(1.000000000000000)
        self.dsBoxEpsilonMin.setSingleStep(0.000010000000000)
        self.dsBoxEpsilonMin.setValue(0.000000000000000)
        self.lblTxtNumberGames_11 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_11.setObjectName(u"lblTxtNumberGames_11")
        self.lblTxtNumberGames_11.setGeometry(QRect(10, 580, 241, 21))
        self.lblTxtNumberGames_12 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_12.setObjectName(u"lblTxtNumberGames_12")
        self.lblTxtNumberGames_12.setGeometry(QRect(10, 710, 241, 21))
        self.sBoxMiniBatchSize = QSpinBox(self.gbTrainingParameter)
        self.sBoxMiniBatchSize.setObjectName(u"sBoxMiniBatchSize")
        self.sBoxMiniBatchSize.setGeometry(QRect(250, 710, 100, 22))
        self.sBoxMiniBatchSize.setFont(font2)
        self.sBoxMiniBatchSize.setMinimum(1)
        self.sBoxMiniBatchSize.setMaximum(100000)
        self.sBoxMiniBatchSize.setValue(1024)
        self.sBoxTrainEveryXSteps = QSpinBox(self.gbTrainingParameter)
        self.sBoxTrainEveryXSteps.setObjectName(u"sBoxTrainEveryXSteps")
        self.sBoxTrainEveryXSteps.setGeometry(QRect(250, 740, 100, 22))
        self.sBoxTrainEveryXSteps.setFont(font2)
        self.sBoxTrainEveryXSteps.setMinimum(1)
        self.sBoxTrainEveryXSteps.setMaximum(10000)
        self.sBoxTrainEveryXSteps.setValue(16)
        self.lblTxtNumberGames_13 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_13.setObjectName(u"lblTxtNumberGames_13")
        self.lblTxtNumberGames_13.setGeometry(QRect(10, 740, 241, 21))
        self.lblTxtNumberGames_14 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_14.setObjectName(u"lblTxtNumberGames_14")
        self.lblTxtNumberGames_14.setGeometry(QRect(10, 770, 241, 21))
        self.sBoxUpdateTargetEvery = QSpinBox(self.gbTrainingParameter)
        self.sBoxUpdateTargetEvery.setObjectName(u"sBoxUpdateTargetEvery")
        self.sBoxUpdateTargetEvery.setGeometry(QRect(250, 770, 100, 22))
        self.sBoxUpdateTargetEvery.setFont(font2)
        self.sBoxUpdateTargetEvery.setMinimum(1)
        self.sBoxUpdateTargetEvery.setMaximum(100000)
        self.sBoxUpdateTargetEvery.setValue(5)
        self.dsBoxDiscount = QDoubleSpinBox(self.gbTrainingParameter)
        self.dsBoxDiscount.setObjectName(u"dsBoxDiscount")
        self.dsBoxDiscount.setGeometry(QRect(250, 450, 100, 22))
        self.dsBoxDiscount.setFont(font2)
        self.dsBoxDiscount.setToolTipDuration(-1)
        self.dsBoxDiscount.setMaximum(1.000000000000000)
        self.dsBoxDiscount.setSingleStep(0.010000000000000)
        self.dsBoxDiscount.setValue(0.990000000000000)
        self.lblTxtNumberGames_15 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_15.setObjectName(u"lblTxtNumberGames_15")
        self.lblTxtNumberGames_15.setGeometry(QRect(10, 450, 241, 21))
        self.lblTxtNumberGames_16 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_16.setObjectName(u"lblTxtNumberGames_16")
        self.lblTxtNumberGames_16.setGeometry(QRect(10, 680, 241, 21))
        self.sBoxReplayMemorySize = QSpinBox(self.gbTrainingParameter)
        self.sBoxReplayMemorySize.setObjectName(u"sBoxReplayMemorySize")
        self.sBoxReplayMemorySize.setGeometry(QRect(250, 680, 100, 22))
        self.sBoxReplayMemorySize.setFont(font2)
        self.sBoxReplayMemorySize.setMinimum(1)
        self.sBoxReplayMemorySize.setMaximum(100000)
        self.sBoxReplayMemorySize.setValue(1024)
        self.lblTxtNumberGames_20 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_20.setObjectName(u"lblTxtNumberGames_20")
        self.lblTxtNumberGames_20.setGeometry(QRect(10, 520, 241, 21))
        self.dsBoxLearningRate = QDoubleSpinBox(self.gbTrainingParameter)
        self.dsBoxLearningRate.setObjectName(u"dsBoxLearningRate")
        self.dsBoxLearningRate.setGeometry(QRect(250, 480, 100, 22))
        self.dsBoxLearningRate.setFont(font2)
        self.dsBoxLearningRate.setToolTipDuration(-1)
        self.dsBoxLearningRate.setDecimals(6)
        self.dsBoxLearningRate.setMaximum(1.000000000000000)
        self.dsBoxLearningRate.setSingleStep(0.000001000000000)
        self.dsBoxLearningRate.setValue(0.000001000000000)
        self.lblTxtNumberGames_21 = QLabel(self.gbTrainingParameter)
        self.lblTxtNumberGames_21.setObjectName(u"lblTxtNumberGames_21")
        self.lblTxtNumberGames_21.setGeometry(QRect(10, 480, 241, 21))
        self.btnLoadTrainingParameter.raise_()
        self.cBoxTrainPhase3.raise_()
        self.sBoxNumberGames.raise_()
        self.lblTxtMaxMoves.raise_()
        self.cBoxTrainPhase1.raise_()
        self.lblTxtNumberGames.raise_()
        self.sBoxMaxMoves.raise_()
        self.cBoxTrainPhase2.raise_()
        self.lblTxtTrainingSince_2.raise_()
        self.sBoxRewardMove.raise_()
        self.lblTxtNumberGames_2.raise_()
        self.lblTxtNumberGames_3.raise_()
        self.sBoxRewardOwnMill.raise_()
        self.sBoxRewardEnemyMill.raise_()
        self.lblTxtNumberGames_4.raise_()
        self.lblTxtNumberGames_5.raise_()
        self.sBoxRewardWin.raise_()
        self.sBoxRewardLoss.raise_()
        self.lblTxtNumberGames_6.raise_()
        self.dsBoxEpsilonDecay.raise_()
        self.lblTxtNumberGames_8.raise_()
        self.dsBoxEpsilon.raise_()
        self.btnSaveTrainingParameter.raise_()
        self.lblTxtLoadedTrainingsParameter.raise_()
        self.sBoxNumTrainingInstances.raise_()
        self.lblTxtNumberGames_9.raise_()
        self.sBoxMinReplayMemorySize.raise_()
        self.lblTxtNumberGames_10.raise_()
        self.dsBoxEpsilonMin.raise_()
        self.lblTxtNumberGames_11.raise_()
        self.lblTxtNumberGames_12.raise_()
        self.sBoxMiniBatchSize.raise_()
        self.sBoxTrainEveryXSteps.raise_()
        self.lblTxtNumberGames_13.raise_()
        self.lblTxtNumberGames_14.raise_()
        self.sBoxUpdateTargetEvery.raise_()
        self.dsBoxDiscount.raise_()
        self.lblTxtNumberGames_15.raise_()
        self.lblTxtNumberGames_16.raise_()
        self.sBoxReplayMemorySize.raise_()
        self.lblTxtNumberGames_20.raise_()
        self.dsBoxLearningRate.raise_()
        self.lblTxtNumberGames_21.raise_()
        self.gbTrainingStatus = QGroupBox(self.Training)
        self.gbTrainingStatus.setObjectName(u"gbTrainingStatus")
        self.gbTrainingStatus.setGeometry(QRect(410, 10, 1481, 281))
        self.gbTrainingStatus.setFont(font2)
        self.gbTrainingStatus.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.btnLoadTrainingModel = QPushButton(self.gbTrainingStatus)
        self.btnLoadTrainingModel.setObjectName(u"btnLoadTrainingModel")
        self.btnLoadTrainingModel.setGeometry(QRect(10, 180, 131, 41))
        self.btnLoadTrainingModel.setCheckable(False)
        self.lblTxtActualGames = QLabel(self.gbTrainingStatus)
        self.lblTxtActualGames.setObjectName(u"lblTxtActualGames")
        self.lblTxtActualGames.setGeometry(QRect(10, 100, 341, 21))
        self.btnTrainingStart = QPushButton(self.gbTrainingStatus)
        self.btnTrainingStart.setObjectName(u"btnTrainingStart")
        self.btnTrainingStart.setGeometry(QRect(10, 30, 131, 41))
        self.btnSaveTrainingModel = QPushButton(self.gbTrainingStatus)
        self.btnSaveTrainingModel.setObjectName(u"btnSaveTrainingModel")
        self.btnSaveTrainingModel.setGeometry(QRect(150, 180, 131, 41))
        self.btnTrainingStop = QPushButton(self.gbTrainingStatus)
        self.btnTrainingStop.setObjectName(u"btnTrainingStop")
        self.btnTrainingStop.setGeometry(QRect(150, 30, 131, 41))
        self.btnTrainingStop.setCheckable(False)
        self.lblTxtTrainingSince = QLabel(self.gbTrainingStatus)
        self.lblTxtTrainingSince.setObjectName(u"lblTxtTrainingSince")
        self.lblTxtTrainingSince.setGeometry(QRect(10, 80, 341, 21))
        self.pbarTraining = QProgressBar(self.gbTrainingStatus)
        self.pbarTraining.setObjectName(u"pbarTraining")
        self.pbarTraining.setGeometry(QRect(10, 150, 271, 23))
        self.pbarTraining.setValue(24)
        self.lblTxtLoadedTrainingModel = QLabel(self.gbTrainingStatus)
        self.lblTxtLoadedTrainingModel.setObjectName(u"lblTxtLoadedTrainingModel")
        self.lblTxtLoadedTrainingModel.setGeometry(QRect(10, 230, 1471, 21))
        self.btnResetTrainingModel = QPushButton(self.gbTrainingStatus)
        self.btnResetTrainingModel.setObjectName(u"btnResetTrainingModel")
        self.btnResetTrainingModel.setGeometry(QRect(290, 180, 131, 41))
        self.frmPlotTraining = QFrame(self.Training)
        self.frmPlotTraining.setObjectName(u"frmPlotTraining")
        self.frmPlotTraining.setGeometry(QRect(410, 300, 1481, 551))
        self.frmPlotTraining.setStyleSheet(u"/*border-color: rgb(215, 35, 5);*/\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.frmPlotTraining.setFrameShape(QFrame.StyledPanel)
        self.frmPlotTraining.setFrameShadow(QFrame.Raised)
        self.tabWidget.addTab(self.Training, "")
        self.Validierung = QWidget()
        self.Validierung.setObjectName(u"Validierung")
        self.gbValidierungStatus = QGroupBox(self.Validierung)
        self.gbValidierungStatus.setObjectName(u"gbValidierungStatus")
        self.gbValidierungStatus.setGeometry(QRect(410, 10, 1481, 281))
        self.gbValidierungStatus.setFont(font2)
        self.gbValidierungStatus.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.lblTxtValidationActualGames = QLabel(self.gbValidierungStatus)
        self.lblTxtValidationActualGames.setObjectName(u"lblTxtValidationActualGames")
        self.lblTxtValidationActualGames.setGeometry(QRect(10, 200, 341, 21))
        self.btnValidationStart = QPushButton(self.gbValidierungStatus)
        self.btnValidationStart.setObjectName(u"btnValidationStart")
        self.btnValidationStart.setGeometry(QRect(10, 130, 131, 41))
        self.btnValidationStop = QPushButton(self.gbValidierungStatus)
        self.btnValidationStop.setObjectName(u"btnValidationStop")
        self.btnValidationStop.setGeometry(QRect(150, 130, 131, 41))
        self.btnValidationStop.setCheckable(False)
        self.lblTxtValidationSince = QLabel(self.gbValidierungStatus)
        self.lblTxtValidationSince.setObjectName(u"lblTxtValidationSince")
        self.lblTxtValidationSince.setGeometry(QRect(10, 180, 341, 21))
        self.pbarValidation = QProgressBar(self.gbValidierungStatus)
        self.pbarValidation.setObjectName(u"pbarValidation")
        self.pbarValidation.setGeometry(QRect(10, 240, 271, 23))
        self.pbarValidation.setValue(24)
        self.btnLoadReferenceModel = QPushButton(self.gbValidierungStatus)
        self.btnLoadReferenceModel.setObjectName(u"btnLoadReferenceModel")
        self.btnLoadReferenceModel.setGeometry(QRect(10, 80, 131, 41))
        self.btnLoadReferenceModel.setCheckable(False)
        self.btnLoadValidationModel = QPushButton(self.gbValidierungStatus)
        self.btnLoadValidationModel.setObjectName(u"btnLoadValidationModel")
        self.btnLoadValidationModel.setGeometry(QRect(10, 30, 131, 41))
        self.lblTxtLoadedValidationModel = QLabel(self.gbValidierungStatus)
        self.lblTxtLoadedValidationModel.setObjectName(u"lblTxtLoadedValidationModel")
        self.lblTxtLoadedValidationModel.setGeometry(QRect(150, 50, 1331, 21))
        self.lblTxtLoadedReferenceModel = QLabel(self.gbValidierungStatus)
        self.lblTxtLoadedReferenceModel.setObjectName(u"lblTxtLoadedReferenceModel")
        self.lblTxtLoadedReferenceModel.setGeometry(QRect(150, 100, 1331, 21))
        self.btnLoadValidationModel.raise_()
        self.lblTxtValidationActualGames.raise_()
        self.btnValidationStart.raise_()
        self.btnValidationStop.raise_()
        self.lblTxtValidationSince.raise_()
        self.pbarValidation.raise_()
        self.btnLoadReferenceModel.raise_()
        self.lblTxtLoadedValidationModel.raise_()
        self.lblTxtLoadedReferenceModel.raise_()
        self.gbValidierungsParameter = QGroupBox(self.Validierung)
        self.gbValidierungsParameter.setObjectName(u"gbValidierungsParameter")
        self.gbValidierungsParameter.setGeometry(QRect(10, 10, 391, 841))
        self.gbValidierungsParameter.setFont(font2)
        self.gbValidierungsParameter.setStyleSheet(u"QGroupBox {\n"
"	margin-top: 3ex;\n"
"	border: 1px solid #d72305;	/* Roter Rahmen */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -0.7em;\n"
"	left: 1em;\n"
"}")
        self.cBoxValidationReferenceMovesRandom = QCheckBox(self.gbValidierungsParameter)
        self.cBoxValidationReferenceMovesRandom.setObjectName(u"cBoxValidationReferenceMovesRandom")
        self.cBoxValidationReferenceMovesRandom.setGeometry(QRect(10, 220, 340, 20))
        self.cBoxValidationReferenceMovesRandom.setFont(font2)
        self.cBoxValidationReferenceMovesRandom.setChecked(True)
        self.sBoxValidationNumberGames = QSpinBox(self.gbValidierungsParameter)
        self.sBoxValidationNumberGames.setObjectName(u"sBoxValidationNumberGames")
        self.sBoxValidationNumberGames.setGeometry(QRect(250, 110, 100, 22))
        self.sBoxValidationNumberGames.setFont(font2)
        self.sBoxValidationNumberGames.setMinimum(1)
        self.sBoxValidationNumberGames.setMaximum(99999999)
        self.sBoxValidationNumberGames.setValue(1000)
        self.sBoxValidationNumberGames.setDisplayIntegerBase(10)
        self.lblTxtValidationMaxMoves = QLabel(self.gbValidierungsParameter)
        self.lblTxtValidationMaxMoves.setObjectName(u"lblTxtValidationMaxMoves")
        self.lblTxtValidationMaxMoves.setGeometry(QRect(10, 140, 241, 21))
        self.cBoxValidationRandomReferenceModel = QCheckBox(self.gbValidierungsParameter)
        self.cBoxValidationRandomReferenceModel.setObjectName(u"cBoxValidationRandomReferenceModel")
        self.cBoxValidationRandomReferenceModel.setGeometry(QRect(10, 170, 340, 20))
        self.cBoxValidationRandomReferenceModel.setFont(font2)
        self.cBoxValidationRandomReferenceModel.setChecked(True)
        self.lblTxtNumberGames_19 = QLabel(self.gbValidierungsParameter)
        self.lblTxtNumberGames_19.setObjectName(u"lblTxtNumberGames_19")
        self.lblTxtNumberGames_19.setGeometry(QRect(10, 110, 241, 21))
        self.sBoxValidationMaxMoves = QSpinBox(self.gbValidierungsParameter)
        self.sBoxValidationMaxMoves.setObjectName(u"sBoxValidationMaxMoves")
        self.sBoxValidationMaxMoves.setGeometry(QRect(250, 140, 100, 22))
        self.sBoxValidationMaxMoves.setFont(font2)
        self.sBoxValidationMaxMoves.setMinimum(1)
        self.sBoxValidationMaxMoves.setMaximum(999)
        self.sBoxValidationMaxMoves.setValue(200)
        self.cBoxValidationFirstMoveRandom = QCheckBox(self.gbValidierungsParameter)
        self.cBoxValidationFirstMoveRandom.setObjectName(u"cBoxValidationFirstMoveRandom")
        self.cBoxValidationFirstMoveRandom.setGeometry(QRect(10, 195, 340, 20))
        self.cBoxValidationFirstMoveRandom.setFont(font2)
        self.cBoxValidationFirstMoveRandom.setChecked(True)
        self.btnSaveValidationParameter = QPushButton(self.gbValidierungsParameter)
        self.btnSaveValidationParameter.setObjectName(u"btnSaveValidationParameter")
        self.btnSaveValidationParameter.setGeometry(QRect(150, 30, 131, 41))
        self.btnLoadValidationParameter = QPushButton(self.gbValidierungsParameter)
        self.btnLoadValidationParameter.setObjectName(u"btnLoadValidationParameter")
        self.btnLoadValidationParameter.setGeometry(QRect(10, 30, 131, 41))
        self.btnLoadValidationParameter.setCheckable(False)
        self.lblTxtLoadedValidationParameter = QLabel(self.gbValidierungsParameter)
        self.lblTxtLoadedValidationParameter.setObjectName(u"lblTxtLoadedValidationParameter")
        self.lblTxtLoadedValidationParameter.setGeometry(QRect(10, 80, 381, 21))
        self.sBoxValidationNumValidationInstances = QSpinBox(self.gbValidierungsParameter)
        self.sBoxValidationNumValidationInstances.setObjectName(u"sBoxValidationNumValidationInstances")
        self.sBoxValidationNumValidationInstances.setGeometry(QRect(250, 280, 100, 22))
        self.sBoxValidationNumValidationInstances.setFont(font2)
        self.sBoxValidationNumValidationInstances.setMinimum(1)
        self.sBoxValidationNumValidationInstances.setMaximum(1000)
        self.sBoxValidationNumValidationInstances.setValue(32)
        self.lblTxtNumberGames_27 = QLabel(self.gbValidierungsParameter)
        self.lblTxtNumberGames_27.setObjectName(u"lblTxtNumberGames_27")
        self.lblTxtNumberGames_27.setGeometry(QRect(10, 280, 241, 21))
        self.cBoxValidationSwitchPlayer = QCheckBox(self.gbValidierungsParameter)
        self.cBoxValidationSwitchPlayer.setObjectName(u"cBoxValidationSwitchPlayer")
        self.cBoxValidationSwitchPlayer.setGeometry(QRect(10, 245, 340, 20))
        self.cBoxValidationSwitchPlayer.setFont(font2)
        self.cBoxValidationSwitchPlayer.setChecked(True)
        self.frmPlotValidation = QFrame(self.Validierung)
        self.frmPlotValidation.setObjectName(u"frmPlotValidation")
        self.frmPlotValidation.setGeometry(QRect(410, 300, 1481, 551))
        self.frmPlotValidation.setStyleSheet(u"/*border-color: rgb(215, 35, 5);*/\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.frmPlotValidation.setFrameShape(QFrame.StyledPanel)
        self.frmPlotValidation.setFrameShadow(QFrame.Raised)
        self.tabWidget.addTab(self.Validierung, "")
        self.btnFullScreen = QPushButton(self.centralwidget)
        self.btnFullScreen.setObjectName(u"btnFullScreen")
        self.btnFullScreen.setGeometry(QRect(1780, 0, 75, 23))
        self.btnFenster = QPushButton(self.centralwidget)
        self.btnFenster.setObjectName(u"btnFenster")
        self.btnFenster.setGeometry(QRect(1710, 0, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnClose.clicked.connect(MainWindow.close)
        self.btnFullScreen.clicked.connect(MainWindow.showFullScreen)
        self.btnFenster.clicked.connect(MainWindow.showNormal)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Demonstrator Reinformant Learning", None))
        self.actionWas_ist_das.setText(QCoreApplication.translate("MainWindow", u"Was ist das", None))
        self.actionVollbild.setText(QCoreApplication.translate("MainWindow", u"Vollbild", None))
        self.actionFenster.setText(QCoreApplication.translate("MainWindow", u"Fenster", None))
        self.lblTitel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#d72305;\">Demonstrator reinforcement learning</span></p></body></html>", None))
        self.lblHKALogo.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/h-ka Logos/Ressourcen/HKA_Logo_Gesamt-h_RGB.svg\"/></p></body></html>", None))
        self.lblSpielfeld.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Ressourcen/860px-Nine_Men's_Morris_board - grau.png\"/></p></body></html>", None))
        self.lblSt00.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt01.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblSt02.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblSt10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt21.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt03.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt24.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt25.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt26.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt04.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt05.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt06.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt07.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblSt17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblTxtAvTokens.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Verf\u00fcgbare Spielsteine:</span></p></body></html>", None))
        self.lblAvP20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP21.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP24.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP25.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP26.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP28.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><img src=\":/Spielfeld/Spielstein_Rot\"/></p></body></html>", None))
        self.lblAvP12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.lblAvP15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/Spielfeld/Spielstein_Blau\"/></p></body></html>", None))
        self.btnRestart.setText(QCoreApplication.translate("MainWindow", u"Spiel neustarten", None))
        self.lblNextAction.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">&lt;lblNextAction&gt;</span></p></body></html>", None))
        self.lblTxtNextAction.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">N\u00e4chste Aktion:</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Spielfeld), QCoreApplication.translate("MainWindow", u"Spielfeld", None))
        self.gbPlayer.setTitle(QCoreApplication.translate("MainWindow", u"Spieler", None))
        self.rBtnPlayer1Human.setText(QCoreApplication.translate("MainWindow", u"Mensch", None))
        self.rBtnPlayer1KI.setText(QCoreApplication.translate("MainWindow", u"KI", None))
        self.lblTxtNextAction_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spieler 1:</span></p></body></html>", None))
        self.lblTxtNextAction_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spieler 2:</span></p></body></html>", None))
        self.rBtnPlayer2Human.setText(QCoreApplication.translate("MainWindow", u"Mensch", None))
        self.rBtnPlayer2KI.setText(QCoreApplication.translate("MainWindow", u"KI", None))
        self.btnLoadKIData1.setText(QCoreApplication.translate("MainWindow", u"KI Daten laden", None))
        self.btnLoadKIData2.setText(QCoreApplication.translate("MainWindow", u"KI Daten laden", None))
        self.lblTxtLoadeFilePath1.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.lblTxtLoadeFilePath2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.btnSettingSave.setText(QCoreApplication.translate("MainWindow", u"Speichern", None))
        self.gbPlayer_2.setTitle(QCoreApplication.translate("MainWindow", u"KI gegen KI", None))
        self.lblTxtNumberGames_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Zuggeschwindigkeit:</span></p></body></html>", None))
        self.lblTxtNumberGames_18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">s</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Einstellungen), QCoreApplication.translate("MainWindow", u"Einstellungen", None))
        self.gbTrainingParameter.setTitle(QCoreApplication.translate("MainWindow", u"Trainingsparameter", None))
        self.cBoxTrainPhase3.setText(QCoreApplication.translate("MainWindow", u"Spielphase 3 (springen) trainieren", None))
        self.lblTxtMaxMoves.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Max. Z\u00fcge pro Spiel:</span></p></body></html>", None))
        self.cBoxTrainPhase1.setText(QCoreApplication.translate("MainWindow", u"Spielphase 1 (setzen) trainieren", None))
        self.lblTxtNumberGames.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Anzahl zu trainierender Spiele:</span></p></body></html>", None))
        self.cBoxTrainPhase2.setText(QCoreApplication.translate("MainWindow", u"Spielphase 2 (bewegen) trainieren", None))
        self.lblTxtTrainingSince_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Hyperparameter:</span></p></body></html>", None))
        self.lblTxtNumberGames_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Reward Zug:</span></p></body></html>", None))
        self.lblTxtNumberGames_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Reward eigene M\u00fchle:</span></p></body></html>", None))
        self.lblTxtNumberGames_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Reward gegnerische M\u00fchle:</span></p></body></html>", None))
        self.lblTxtNumberGames_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Reward Sieg:</span></p></body></html>", None))
        self.lblTxtNumberGames_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Reward Niederlage:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.dsBoxEpsilonDecay.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.lblTxtNumberGames_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Epsilon prozentuale Abnahme:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.dsBoxEpsilon.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.btnSaveTrainingParameter.setText(QCoreApplication.translate("MainWindow", u"Parameter speichern", None))
#if QT_CONFIG(tooltip)
        self.btnLoadTrainingParameter.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.btnLoadTrainingParameter.setText(QCoreApplication.translate("MainWindow", u"Parameter laden", None))
        self.lblTxtLoadedTrainingsParameter.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.lblTxtNumberGames_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Training-Instanzen:</span></p></body></html>", None))
        self.lblTxtNumberGames_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spielzug min. Puffergr\u00f6\u00dfe:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.dsBoxEpsilonMin.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.lblTxtNumberGames_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Epsilon minimal:</span></p></body></html>", None))
        self.lblTxtNumberGames_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Trainingsdaten Puffergr\u00f6\u00dfe:</span></p></body></html>", None))
        self.lblTxtNumberGames_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Trainiere nach Anzahl Z\u00fcge:</span></p></body></html>", None))
        self.lblTxtNumberGames_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Aktualisiere Ziel-Modell nach:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.dsBoxDiscount.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dsBoxDiscount.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.lblTxtNumberGames_15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Discount-Faktor &lambda;:</span></p></body></html>", None))
        self.lblTxtNumberGames_16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spielzug Puffergr\u00f6\u00dfe:</span></p></body></html>", None))
        self.lblTxtNumberGames_20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Epsilon:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.dsBoxLearningRate.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dsBoxLearningRate.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.lblTxtNumberGames_21.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Lernrate:</span></p></body></html>", None))
        self.gbTrainingStatus.setTitle(QCoreApplication.translate("MainWindow", u"Trainieren", None))
        self.btnLoadTrainingModel.setText(QCoreApplication.translate("MainWindow", u"Modell laden", None))
        self.lblTxtActualGames.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spiel 0 von 1</span></p></body></html>", None))
        self.btnTrainingStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btnSaveTrainingModel.setText(QCoreApplication.translate("MainWindow", u"Modell speichern", None))
        self.btnTrainingStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.lblTxtTrainingSince.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Training l\u00e4uft seit 00:00:00 hh:mm:ss</span></p></body></html>", None))
        self.lblTxtLoadedTrainingModel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.btnResetTrainingModel.setText(QCoreApplication.translate("MainWindow", u"Neues Modell", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Training), QCoreApplication.translate("MainWindow", u"Training", None))
        self.gbValidierungStatus.setTitle(QCoreApplication.translate("MainWindow", u"Validieren", None))
        self.lblTxtValidationActualGames.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Spiel 0 von 1</span></p></body></html>", None))
        self.btnValidationStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btnValidationStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.lblTxtValidationSince.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Validierung l\u00e4uft seit 00:00:00 hh:mm:ss</span></p></body></html>", None))
        self.btnLoadReferenceModel.setText(QCoreApplication.translate("MainWindow", u"Referenzmodell laden", None))
        self.btnLoadValidationModel.setText(QCoreApplication.translate("MainWindow", u"Validierungsmodell laden", None))
        self.lblTxtLoadedValidationModel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.lblTxtLoadedReferenceModel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.gbValidierungsParameter.setTitle(QCoreApplication.translate("MainWindow", u"Validierungsparameter", None))
        self.cBoxValidationReferenceMovesRandom.setText(QCoreApplication.translate("MainWindow", u"Referenzz\u00fcge zuf\u00e4llig", None))
        self.lblTxtValidationMaxMoves.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Max. Z\u00fcge pro Spiel:</span></p></body></html>", None))
        self.cBoxValidationRandomReferenceModel.setText(QCoreApplication.translate("MainWindow", u"Zuf\u00e4lliges Referenzmodell", None))
        self.lblTxtNumberGames_19.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Anzahl zu validierende Spiele:</span></p></body></html>", None))
        self.cBoxValidationFirstMoveRandom.setText(QCoreApplication.translate("MainWindow", u"Erster Zug zuf\u00e4llig", None))
        self.btnSaveValidationParameter.setText(QCoreApplication.translate("MainWindow", u"Parameter speichern", None))
        self.btnLoadValidationParameter.setText(QCoreApplication.translate("MainWindow", u"Parameter laden", None))
        self.lblTxtLoadedValidationParameter.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Geladen:</span></p></body></html>", None))
        self.lblTxtNumberGames_27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Validierungs-Instanzen:</span></p></body></html>", None))
        self.cBoxValidationSwitchPlayer.setText(QCoreApplication.translate("MainWindow", u"Spielernummer abwechseln", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Validierung), QCoreApplication.translate("MainWindow", u"Validierung", None))
        self.btnFullScreen.setText(QCoreApplication.translate("MainWindow", u"Vollbild", None))
        self.btnFenster.setText(QCoreApplication.translate("MainWindow", u"Fenster", None))
    # retranslateUi

